version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:13.14
      - image: docker # Or a more recent version
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
        environment:
          DOCKER_AUTH: '{"auths": {"https://index.docker.io/v1/": {"auth": "<encoded_auth>"}}}'
    steps:
      - checkout
      - run:
          name: Check Docker version
          command: docker --version
      - run:
          name: Install Docker Compose
          command: |
            # Add Docker's official GPG key:
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
            chmod a+r /etc/apt/keyrings/docker.asc

            # Add the repository to Apt sources:
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install docker-ce-cli docker-buildx-plugin docker-compose-plugin

      - setup_remote_docker #activate the remote docker environment
      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose-build.yaml build --parallel
      - run:
          name: Start Docker Compose services
          command: docker-compose up -d # -d to run in detached mode
      - run:
          name: Docker Login and Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push deemsameer/udagram-frontend
            docker push deemsameer/udagram-api-feed
            docker push deemsameer/udagram-api-user
            docker push deemsameer/reverseproxy
workflows:
  version: 2
  build-and-push:
    jobs:
      - build