version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:13.14
      - image: docker
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
        environment:
          DOCKER_AUTH: '{"auths": {"https://index.docker.io/v1/": {"auth": "<encoded_auth>"}}}'
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17 #or a more recent version.
      - run:
          name: Check Docker version
          command: docker --version
      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose-build.yaml build --parallel
      - run:
          name: Start Docker Compose services
          command: docker-compose up -d # -d to run in detached mode
      - run:
          name: Docker Login and Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push deemsameer/udagram-frontend
            docker push deemsameer/udagram-api-feed
            docker push deemsameer/udagram-api-user
            docker push deemsameer/reverseproxy
workflows:
  version: 2
  build-and-push:
    jobs:
      - build