apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: default  # Adjust namespace if needed
type: Opaque
data:
  # The values must be base64 encoded
  aws_access_key_id: QUtJQVdIVDJSVFhKNUVNNFlHWFY=
  aws_secret_access_key: OVlvcW1lMHYyVHh1enZzcEZac1lEM2dxWCtNd000VnZNb3I3T0gxMQ==
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVdIVDJSVFhKNUVNNFlHWFYK