apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-app
  labels:
    app: reverseproxy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy-app
  template:
    metadata:
      labels:
        app: reverseproxy-app
    spec:
      containers:
      - name: reverseproxy
        image: deemsameer/reverseproxy
        ports:
        - containerPort: 80